config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :donations do
    get :sync
  end
  namespace :admin do
      resources :users
      resources :announcements
      resources :notifications
      resources :services

      root to: "users#index"
    end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @donations = Donation.where(status: :payout_proccessed)
  end

  def terms
  end

  def privacy
  end

  def donations
  end
end

app/views/home/index.html.erb
<h1>IOTA Donation Manager</h1>
<p class="lead">This is a manager, which helps you to distribute donations. <br> You can test it here to donate to the einfachIOTA team! ;)</p>
<%= link_to "Become a sponsor", new_donation_url, class: "btn btn-primary" %>
<h2>List of Donators</h2>
<div class="card-deck">
  <% @donations.each do |donation| %>

  <div class="card">
    <img class="card-img-top" src="https://via.placeholder.com/100" alt="Card image">
    <div class="card-body">
      <h4 class="card-title"><%= donation.name %></h4>
      <p class="card-text"><%= donation.message %></p>
      <a href="#" class="btn btn-primary">See Profile</a>
      <a href="https://devnet.thetangle.org/bundle/<%= donation.bundleHash %>" target="_blank">TheTangle.org</a>
      <%= link_to "More information", donation_path(donation) %>
    </div>
  </div>
  <% end %>
</div>

app/views/home/privacy.html.erb
<h1>Privacy Policy</h1>
<p class="lead">Use this for your Privacy Policy</p>

app/views/home/terms.html.erb
<h1>Terms of Service</h1>
<p class="lead">Use this for your Terms of Service</p>