config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :donations do
    get :sync
  end
  namespace :admin do
      resources :users
      resources :announcements
      resources :notifications
      resources :services

      root to: "users#index"
    end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/donation.rb
class Donation < ApplicationRecord
  require 'iota'
  serialize :distributon_data, JSON

  before_create :create_address, :fetch_distributions

  enum status: [:waiting, :payout_in_progress, :payout_proccessed]

  def sync!
    return unless self.waiting?
    # Create client directly with provider
    client = IOTA::Client.new(provider: 'https://nodes.devnet.thetangle.org:443')
    account = IOTA::Models::Account.new(client, self.seed)
    account.getAccountDetails({})
    pp "balance"
    pp account.balance

    if account.balance > 0
      pp "donated!"
      self.payout_in_progress!
      DonationDistributionJob.perform_later(self)
    else
      pp "not donated!"
    end

  end

  private
  def create_address
    # Create client directly with provider
    client = IOTA::Client.new(provider: 'https://nodes.devnet.thetangle.org:443')

    # now you can start using all of the functions
    status, data = client.api.getNodeInfo

    ## create and save seed
    self.seed = (1..81).map{'ABCDEFGHIJKLMNOPQRSTUVWXYZ9'[SecureRandom.random_number(27)]}.join('')

    ## create and save latest address
    account = IOTA::Models::Account.new(client, self.seed)
    account.getAccountDetails({})

    self.address = account.latestAddress
    self.status = :waiting
  end

  def fetch_distributions
    uri = URI("#{Rails.configuration.pool_manager_url}/get_node_payout_data.json")
    response =  Net::HTTP.get(uri)# => String
    self.distributon_data = JSON.parse(response)

  end

end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  layout "popup"
  before_action :set_donation, only: [:show, :edit, :update, :destroy]

  # GET /donations
  # GET /donations.json
  def index
    @donations = Donation.where(status: :payout_proccessed).order(created_at: :desc)
  end

  # GET /donations/1
  # GET /donations/1.json
  def show
  end

  # GET /donations/new
  def new
    @donation = Donation.new
  end

  # POST /donations
  # POST /donations.json
  def create
    @donation = Donation.new(donation_params)
    respond_to do |format|
      if @donation.save
        format.html { redirect_to @donation, notice: 'Donation was successfully created.' }
        format.json { render :show, status: :created, location: @donation }
      else
        format.html { render :new }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donations/1
  # PATCH/PUT /donations/1.json
  def update
    respond_to do |format|
      if @donation.update(donation_params)
        format.html { redirect_to @donation, notice: 'Donation was successfully updated.' }
        format.json { render :show, status: :ok, location: @donation }
      else
        format.html { render :edit }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1
  # DELETE /donations/1.json
  def destroy
    @donation.destroy
    respond_to do |format|
      format.html { redirect_to donations_url, notice: 'Donation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def sync
    @donation = Donation.find(params[:donation_id])
    @donation.sync!
    redirect_to donation_path(@donation)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donation
      @donation = Donation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donation_params
      params.require(:donation).permit(:name, :message, :link, :distributon_data)
    end
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/_form.html.erb
<%= form_with(model: donation, local: true) do |form| %>
  <% if donation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(donation.errors.count, "error") %> prohibited this donation from being saved:</h2>

      <ul>
      <% donation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, "Your name:" %>
    <%= form.text_field :name, class: 'form-control', placeholder: 'Donator3000' %>
  </div>

  <div class="form-group">
    <%= form.label :message, "Donation Message:" %>
    <%= form.text_field :message, class: 'form-control', placeholder: 'I like this project!' %>
  </div>

  <div class="form-group">
    <%= form.label :link, "Link to your website:" %>
    <%= form.text_field :link, class: 'form-control', placeholder: 'https://www.einfachiota.de' %>
  </div>

  <div class="form-group">
    <% if donation.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', donation, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <p>TODO: Im not a robot</p>

    <%= form.submit class: 'btn btn-primary' %>

    <% if donation.persisted? %>
      <%= link_to "Cancel", donation, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Close", "#", class: "btn btn-link", onClick: "ClosePopup()" %>
    <% end %>
  </div>
<% end %>
<script type="text/javascript">
  function ClosePopup() {
    var win = window.close();
  }
</script>

app/views/donations/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Donations</h1>
  </div>

  <div class="col-sm-6 text-right">
  <%= link_to new_donation_path, class: 'btn btn-primary' do %>
    Add New Donation
  <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>


            <th>Id</th>
            <th>Name</th>
            <th>Status</th>

          <th></th>

      </tr>
    </thead>

    <tbody>
      <% @donations.each do |donation| %>
        <%= content_tag :tr, id: dom_id(donation), class: dom_class(donation) do %>


                      <td><%= donation.id %></td>
                      <td><%= donation.name %></td>
                      <td><%= donation.status %></td>


            <td><%= link_to 'Show', donation %></td>

        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/donations/new.html.erb
<h1>Become a donator!</h1>
<p>You can fill in this data, to show some informations about you on the dontion list.</p>
<p>Leave it all blank, to donate anonyous.</p>

<%= render 'form', donation: @donation %>

app/views/donations/show.html.erb
<div class="page-header">
  <%= link_to donations_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    All Donations
  <% end %>
  <h1>Show donation</h1>
</div>
<p>Status:<%= @donation.status %></p>
<% if @donation.waiting? %>

  <%= link_to "Sync Donation", donation_sync_path(@donation), class: "btn btn-primary"  %>

  <dl class="dl-horizontal">

    <dt>Name:</dt>
    <dd><%= @donation.name %></dd>

    <dt>Message:</dt>
    <dd><%= @donation.message %></dd>

    <dt>Link:</dt>
    <dd><%= @donation.link %></dd>

    <dt>Address:</dt>
    <dd><%= @donation.address %></dd>


  </dl>




  <%= react_component("DonationHelper", { address: @donation.address }) %>

<% elsif @donation.payout_in_progress? %>
  <p>Payout processing...</p>
<% elsif @donation.payout_proccessed? %>
  <p>Payout done</p>
  <a href="https://devnet.thetangle.org/bundle/<%= @donation.bundleHash %>" target="_blank"></a>
<% end %>


<h5>Donation will be distributed to the following participants:</h5>
<div class="alert alert-warning" role="alert">
  The donation will be distributed if the donation transaction is confirmed.
  So the data below is just a example and the real distribution could be a bit different.
</div>
<table class="table table-hover">
  <thead>
    <th>Name</th>
    <th>Points</th>
    <th>Shares</th>
  </thead>
  <tbody>
    <% @donation.distributon_data["entries"].each do |entry| %>
    <tr>
      <td><%= entry["name"] %></td>
      <td><%= entry["points"] %></td>
      <td><%= "~#{(entry["share"] * 100).round(2)}%" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

</ul>